name: Export ASINs to Excel

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install deps
        run: pip install pandas openpyxl
      - name: Run export
        run: python3 export_asins.py
      - name: Upload Excel artifact
        uses: actions/upload-artifact@v4
        with:
          name: asins-excel
          path: asins.xlsx
